### ISSUE TITLE
Cloud vision API switch moved

### ISSUE THREAD

**Issue by max-ostapenko** [googlecodelabs/mlkit-android#12]
Hi Kalyan,
Thanks for a workshop!

There is no need to go to GCP to turn on Cloud Vision API anymore. ([codelab screen](https://codelabs.developers.google.com/codelabs/mlkit-android/#10)).
You should do it directly from Firebase interface, [APIs tab](https://console.firebase.google.com/u/0/project/ml-kit-codelab/ml/apis).

**Comment by calren** [comment]
The codelabs in this repo no longer support Cloud APIs anymore, so I'm going to go ahead and close this issue.
