### ISSUE TITLE
The up-to-date dependencies do not work with the code

### ISSUE THREAD

**Issue by ViktorPalmason** [googlecodelabs/mlkit-android#36]
Updating these dependencies:
- implementation 'com.google.firebase:firebase-ml-vision:19.0.3'
- implementation 'com.google.firebase:firebase-ml-vision-image-label-model:17.0.2'
- implementation 'com.google.firebase:firebase-ml-vision-face-model:17.0.2'
- implementation 'com.google.firebase:firebase-ml-model-interpreter:18.0.0'

To the up-to-date dependencies:
- implementation 'com.google.firebase:firebase-ml-vision:24.0.2'
- implementation 'com.google.firebase:firebase-ml-vision-image-label-model:20.0.0'
- implementation 'com.google.firebase:firebase-ml-vision-face-model:20.0.0'
- implementation 'com.google.firebase:firebase-ml-model-interpreter:22.0.2'

Stops the code from running

I get theses error messages:

>MainActivity.java:49:  error: cannot find symbol
import com.google.firebase.ml.custom.FirebaseModelOptions;
  symbol:   class FirebaseModelOptions

>MainActivity.java:286: error: cannot find symbol
            FirebaseRemoteModel remoteModel = new FirebaseRemoteModel.Builder
  symbol:   class Builder

>MainActivity.java:298: error: cannot find symbol
            manager.registerRemoteModel(remoteModel);
  symbol:   method registerRemoteModel(FirebaseRemoteModel)

>MainActivity.java:299: error: cannot find symbol
            manager.registerLocalModel(localModel);
  symbol:   method registerLocalModel(FirebaseLocalModel)

>MainActivity.java:300: error: cannot find symbol
            FirebaseModelOptions modelOptions =
  symbol:   class FirebaseModelOptions

>MainActivity.java:301: error: package FirebaseModelOptions does not exist
                    new FirebaseModelOptions.Builder()

**Comment by calren** [comment]
Hey @ViktorPalmason , we've completely revamped some of the code for these codelabs! I believe this shouldn't be an issue anymore, so I'm going to go ahead and close this issue for now. But feel free to reopen if you end up still seeing the same problem.
