### ISSUE TITLE
CODE ISSUE

### ISSUE THREAD

**Issue by kumaradityaka** [googlecodelabs/mlkit-android#37]
ALL THE CODE ARE KOTLIN AND NOT JAVA!
ITS MENTIONED .java FILE and THE CODE IS IN KOTLIN?!

**Comment by calren** [comment]
Hey @kumaradityaka , unfortunately we do not have plans to add a similar Java version for these codelabs for now. You can, however, check out our samples that are separate from codelabs here : https://github.com/googlesamples/mlkit/tree/master/android . These samples do have Java implementations!
